version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "pub"
    directory: "/packages/gcp_secret_manager"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/packages/secret_manager"
    schedule:
      interval: "monthly"

