name: secret_manager
description: Access your secrets no matter where they're stored.
version: 0.0.1-dev.1
homepage: https://github.com/Morel-Tech/secret_manager_dart
repository: https://github.com/Morel-Tech/secret_manager_dart
issue_tracker: https://github.com/Morel-Tech/secret_manager_dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  current_gcp_project: ^0.0.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.3.1
  http: ^1.0.0
  recase: ^4.1.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
