name: secret_manager
description: Access your secrets no matter where they're stored.
version: 1.0.0
homepage: https://github.com/Morel-Tech/secret_manager_dart/tree/main/packages/secret_manager
repository: https://github.com/Morel-Tech/secret_manager_dart/tree/main/packages/secret_manager
issue_tracker: https://github.com/Morel-Tech/secret_manager_dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  platform: ^3.1.6
  recase: ^4.1.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
