name: gcp_secret_manager
description: A secret manager that pulls values from GCP Secret Manager.
version: 1.0.0-dev.1
homepage: https://github.com/Morel-Tech/gcp_secret_manager

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  current_gcp_project: ^0.0.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.3.1
  http: ^1.0.0
  secret_manager: ^0.0.1-dev.1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  secret_manager:
    path: ../secret_manager
