name: Secret Manager

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/secret_manager_verify_and_test.yaml"
      - "packages/secret_manager/**"

  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "packages/secret_manager/**"


jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@main
    with:
      working_directory: packages/secret_manager
      dart_sdk: stable
      min_coverage: 100
